on: [push]

jobs:
  dependency_analysis:
    runs-on:  ubuntu-latest
    name: Test dependencies for security flaws
    steps:
      - uses: actions/checkout@v2
      - name: Dependency Security
        run: pip3 install safety && safety check
        shell: bash
  code_analysis:
    runs-on:  ubuntu-latest
    name: Analyse code for security flaws
    steps:
      - name: Code Security Analysis
        uses: actions/checkout@v2
        run: |
          # pip3 install semgrep && semgrep --max-lines-per-finding 0 --config "./.semgrep/" --error -o ~/abc/custom.txt
          pip3 install semgrep && semgrep --max-lines-per-finding 0 --config "p/owasp-top-ten" --error -o ott.txt
          # semgrep --max-lines-per-finding 0 --config "p/nodejsscan" --error -o ~/abc/njsscan.txt
        shell: bash
        
      - name: Upload
        uses: actions/upload-artifact@v3      
        with:
          name: scan-results
          path: ott.txt
        
  deploy:
    name: Deploy
    needs: [dependency_analysis, code_analysis]
    runs-on: ubuntu-latest
    steps:
    - name: Will not run until issues resolved
      run: |
        echo "Deployed...Success."


    
